### ISSUE TITLE
Says "unofficial build" even after update

### ISSUE THREAD

**Issue by frederikaalund** [wurstscript/WurstSetup#27] opened 2019-03-05 19:42 UTC
Looks like this:
![image](https://user-images.githubusercontent.com/545423/53832565-e4e6a880-3f86-11e9-819b-0dac4eb9bbf1.png)

I tried deleting the `.wurst` folder and install wurst again but I still get "unofficial build". When I call `wurst.exe --version` I get `1091`, as expected.

Is this the expected behaviour?

**Comment by Frotty** [comment] 2019-03-05 19:45
No, and I cannot reproduce it:
![](https://i.imgur.com/ckvMnu9.jpg)
Make sure vscode is closed when updating. Also check task manager for still open java processes which might lock files.

**Comment by frederikaalund** [comment] 2019-03-05 19:56
Thanks for the quick reply.

> Make sure vscode is closed when updating

I've done that.

> Also check task manager for still open java processes which might lock files.

Done. Only jusched.exe was running (which I figured was harmless but closed anyhow).

> Did you try running from shell?

I've tried running the installer from an Administrator command prompt. This gives the following result:
![image](https://user-images.githubusercontent.com/545423/53833412-b964bd80-3f88-11e9-8b5e-0008eaf61460.png)

Note the `Installation is custom` log entry.

**Comment by frederikaalund** [comment] 2019-03-05 19:57
I guess that [this line](https://github.com/wurstscript/WurstSetup/blob/d37263b6eab17ff26857cfcc05cb7a75d79a4ce7/src/main/kotlin/global/InstallationManager.kt#L48) throws an error.

**Comment by frederikaalund** [comment] 2019-03-05 20:04
I have a possible cause on [this line](https://github.com/wurstscript/WurstSetup/blob/d37263b6eab17ff26857cfcc05cb7a75d79a4ce7/src/main/kotlin/global/InstallationManager.kt#L65):

    val proc = Runtime.getRuntime().exec("java -jar " + compilerJar.toAbsolutePath() + " --version")

I assume that the command line evaluates to the following on my system:

    java -jar C:\Users\Frederik Aalund\.wurst\wurstscript.jar --version

that results in the error `Error: Unable to access jarfile C:\Users\Frederik`.

This issue can be easily fixed by adding double quotes around the command as follows:

    java -jar "C:\Users\Frederik Aalund\.wurst\wurstscript.jar" --version

that returns `1.8.0.0-jenkins-Wurst-1091`.

**Comment by Frotty** [comment] 2019-03-17 20:44
fixed by #26

**Closed by Frotty** 2019-03-17 20:44 UTC
