### ISSUE TITLE
Exclamation mark in path ("../!/..") breaks java — "D:\Program Files\Warcraft III\!\Wurst\WurstSetup.jar"

### ISSUE THREAD

**Issue by 3ICE** [wurstscript/WurstSetup#20] opened 2018-08-07 10:28 UTC
Hi,

First run of WurstSetup.jar crashed because I had a /!/ in the path. (I keep all my tools in a folder named "!", for example C:\Warcraft III\\!\JNGP\ — but Java tools don't like that.) Workaround: I simply moved Wurst to \Documents\Wurst\ to fix the crash. Works fine now.

The crash was:
"Sorry, Exception occured :(" — SunAwtDialog — javaw.exe
```
Please report this crash with the following info:
Version: 1.1.5.0-jenkins-WurstSetup-71
java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(Unknown Source)
	at ui.MainWindow$exitIcon$2.invoke(MainWindow.kt:42)
	at ui.MainWindow$exitIcon$2.invoke(MainWindow.kt:40)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ui.MainWindow.getExitIcon(MainWindow.kt)
	at ui.MainWindow.access$getExitIcon$p(MainWindow.kt:40)
	at ui.MainWindow$UI.<init>(MainWindow.kt:106)
	at ui.MainWindow$ui$2.invoke(MainWindow.kt:49)
	at ui.MainWindow$ui$2.invoke(MainWindow.kt:40)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ui.MainWindow.getUi(MainWindow.kt)
	at ui.MainWindow.init(MainWindow.kt:68)
	at ui.UiManager$initUI$1.run(UiManager.kt:13)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
occured is spelled occurred, by the way :) Two r's. (The title of that SunAwtDialog above)
I make the same mistake all the time. One r feels right:
occur + ed
But I assure you (and myself over and over...) that it's two: [google.com/search?q=occured](https://www.google.com/search?q=occured) vs [google.com/search?q=occurred](https://www.google.com/search?q=occurred)
occur + red

-----

Another device, same problem:

The location I ran the jar from was again, not _simple_ enough:
"D:\Program Files\Warcraft III\\!\Wurst\WurstSetup.jar"

I continue to believe that the single exclamation mark in the path (as a folder name) is the cause. It's not handled properly. This is either a bug in a library (javax? kotlin? awt? security?) or Wurst (or java itself.)

After adding the "!" folder as a network drive to get a simpler path: "W:\Wurst\WurstSetup.jar", everything works!

(W:\ is symlinked to "D:\Program Files\Warcraft III\\!\")

Not sure if we want to even fix this at all. Ignore and forget as a Known bug.
Who else but me has folders named "!" after all? No one, that's who.
But definitely an interesting, unexpected crash.

Sincerely,
Daniel "3ICE" Berezvai

p.s.: Similar issue:
http://gex.eeve.org/board/viewtopic.php?f=23&t=3346

p.p.s.: Protip: Github escapes \\! to \!, so to keep \\! you should instead write \\\\! (Oh, and and to write that last  \\\\! ... I had to actually write ```\\\\!``` haha double escape nightmare.)

p.p.p.s.: Github employee reading this, please compare:
Warcraft\!\Wurst (\\!\ not escaped)
Warcraft\\!\Wurst (\\!\ correctly escaped as \\\\!\\)
And document accordingly. Thank you.

```\\\\!\\)```

**Comment by Frotty** [comment] 2018-08-07 10:35
Yeah, the exception is mysterious. I personally have not experienced it on several devices, and I'm not sure what's the cause.
Stack-overflow threads etc. don't yield any solution. Really strange.

Anyway thanks, I will take a look regarding the `!` in filepaths. 👍

**Comment by Frotty** [comment] 2020-01-23 20:05
Actually a still unfixed java issue where `!` is used a separator at the end of paths. so `!x` will work, but `x!` not. Closing.

p.s. Did you ever make a wurst map @3ICE ?

**Closed by Frotty** 2020-01-23 20:05 UTC
